#!/bin/bash
#
# merge_subPR
# ===========
#
# Small script to merge an open pull request from the submodule.
#
# Pre-Requisite: have github cli installed (https://cli.github.com/)
#
# This script is intended as counterpart to the request script.
# Once the opened pull request in the source has been merged back,
# this script is meant to be used to close the accompanying PR that
# was created for this change.
# After the PR in the submodule has been closed, update the repository
# to the main branch there.
# Then run merge_subPR in the super directory while on the branch of
# the pull request.
#
# *************************************************************************** #
#
# Copyright (c) 2024 Harald Klimach <harald.klimach@dlr.de>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
# this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
# this list of conditions and the following disclaimer in the documentation
# and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHORS “AS IS” AND ANY EXPRESS OR IMPLIED
# WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL UNIVERSITY OF SIEGEN OR CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# **************************************************************************** #

if ! gh --version &>/dev/null; then
    echo ""
    echo "Need to install github cli (https://cli.github.com/) to close"
    echo "Pull Requests!"
    echo ""
    exit 1
fi

superdir=$(git rev-parse --show-toplevel)
remote=$(cd $superdir && git remote get-url origin 2>/dev/null)
repogit=$(basename $remote 2>/dev/null)
repo=${repogit%.git}

sub=""
case "$repo" in
	"ateles")
		sub="atl"
		;;
	"musubi")
		sub="mus"
		;;
	"seeder")
		sub="sdr"
		;;
	"treelm")
		sub="tem"
		;;
	*)
		echo "Unknown repository $repo!"
		echo "merge_subPR only works for ateles, musubi, seeder or treelm."
		exit 1
		;;
esac


subdir=$superdir/$sub
owd=$(pwd)

if [ -d $subdir ]; then
    cd $subdir
    subbranch=$(git branch --show-current)

    if [ "$subbranch" = "main" ]; then
        submsg=$(git show --pretty=format:%s -s HEAD)
        cd $superdir
        superbranch=$(git branch --show-current)
        echo "Working on $superbranch in $superdir"
        PRnum=$(gh pr status --json number,headRefName --jq '.currentBranch.number')
        PRtitle=$(gh pr status --json title --jq '.currentBranch.title')
        if [ -z "$PRnum" ]; then
            echo "ERROR: There doesn't seem to be a PR for the current branch!"
        else
            echo "This is going to close PR #$PRnum:"
            echo ""
            gh pr view
            echo ""
            echo "Do you want to proceed (y/n)? "
            read proceed
            echo ""
            if [ "$proceed" != "${proceed#[Yy]}" ]; then
                git submodule set-branch --default $sub
                git diff --quiet || git add $sub .gitmodules
                git diff --cached --quiet || git commit -m "$submsg"
                git push && gh pr ready
                gh pr merge --auto -s -t "$PRtitle (#$PRnum)"
            else
                echo ""
                echo "Nothing done. Bye."
                echo ""
            fi
        fi
    else
        echo ""
        echo "The $sub subdirectory has to be on the main branch!"
        echo "But I found:"
        echo "$subbranch in $subdir"
        echo "@: $submsg"
        echo ""
        echo "Can not close the merge request in this state."
        echo ""
    fi
    
else
    echo "merge_subpr only works in the repository that contains"
    echo "the $sub subdirectory."
fi
cd $owd
